### ISSUE TITLE
update readme badges and/or review coveralls coverage

### ISSUE THREAD

**Issue by 7yl4r** [iobis/pyobis#21]
* [ ] look into [coveralls coverage](https://coveralls.io/github/sckott/pyobis?branch=master)
    * does it work w/ gh-actions?
    * is coverage 62%? if so: how to make it 100%?
    * maybe it just needs the badges changed?

**Comment by ayushanand18** [comment]
This is the coverage report after updating all modules and MOF response improvements, and writing tests for them.

![image](https://user-images.githubusercontent.com/36472216/174471895-fe124ceb-9bf1-433a-905d-80127c684be9.png)

**I am not sure how to include tests for obisDownload because I couldn't find an endpoint in the API that returns a ready to download file for the occurrence records. All the other module files have 100% coverage.**

**Comment by ocefpaf** [comment]
I'm OK removing that badge. What do you think @7yl4r?

**Comment by 7yl4r** [comment]
I put a little time into trying to get it working. After ~20min or so I decided the added complications were not worth it.
