### ISSUE TITLE
Add `.get_search_url()` function to all modules

### ISSUE THREAD

**Issue by MathewBiddle** [iobis/pyobis#70]
For each of the modules, we should have the ability to return the API url that is configured with our identified search.

For example,

```python
res = occ.search(taxonid="1363", startdepth=0, enddepth=30, geometry="POLYGON ((-180 -30, 180 -30, 180 30, -180 30, -180 -30))")
```

Then,
```
res.get_search_url()
```
would return
```
https://api.obis.org/v3/occurrence?taxonid=1363&startdepth=0&enddepth=30&geometry=POLYGON%20%28%28-180%20-30%2C%20180%20-30%2C%20180%2030%2C%20-180%2030%2C%20-180%20-30%29%29
```

This gives the user a way to investigate how their query might be not providing the expected responses.

Related to #69

**Comment by ayushanand18** [comment]
That might warrant us to change just the `obisutils.py` file where we render the API response.

**Comment by 7yl4r** [comment]
I like the idea of creating a response class, but I suggest something like `OBISQueryResult` for the name. Python convention is to begin classes with upper-case and to place them in their own module.

**Comment by ayushanand18** [comment]
One issue I am facing is pre-commit returns a coverage 77.1% while the `pytest` powered tests return 100% coverage for all modules.

**Comment by ayushanand18** [comment]
> Here's an initial work on converting each module to its own response class keeping all the methods intact as well. And adding a `get_search_url()` method to return the corresponding API URL. https://github.com/ayushanand18/pyobis/blob/response-class/pyobis/occurrences/occurrences.py

This would look something like this in the docs
![image](https://user-images.githubusercontent.com/36472216/186381382-e7e7aee7-23f3-4090-8ecc-b02637a86d0d.png)

**Comment by MathewBiddle** [comment]
Just so I understand, each module will have this method?

So, for example, `taxa` would be:
```python
from pyobis.taxa import OBISQueryresult as OQR
query = OQR()
data = query.search(scientificname="Mola mola")
api_url = query.get_search_url()
print(api_url)
```

and so on for the other modules?

**Comment by ayushanand18** [comment]
> Just so I understand, each module will have this method?
> 
> So, for example, `taxa` would be:
> 
> ```python
> from pyobis.taxa import OBISQueryresult as OQR
> query = OQR()
> data = query.search(scientificname="Mola mola")
> api_url = query.get_search_url()
> print(api_url)
> ```
> 
> and so on for the other modules?

You are right. Since @7yl4r mentioned that python recommends creating classes for each module in the module itself so I took up this approach (if I understood it right). 

Additionally, we might get into trouble while rendering the `get_mapper_url()` method since not all OBIS endpoints have an equivalent mapper url, and that mapper uses taxonid to fetch records with no scientificname is criterion. We just get to search by scientificname but at the end it renders with taxonid only. So, if a user queries through scientificname in `pyobis` we might need to first fetch the taxon id from worms or any other source. For Eg. for *Mola mola* the obis url might look like `https://api.obis.org/occurrence?scientificname=Mola%20mola` and for mapper it would look like `https://mapper.obis.org/?taxonid=127405`.

**Comment by MathewBiddle** [comment]
Let's deal with the `get_mapper_url()` in #69.
